name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening your first issue! Please ensure you''ve read the [CONTRIBUTING.md](https://github.com/ouropencode/OpenDocumenter/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/ouropencode/OpenDocumenter/blob/master/CODE_OF_CONDUCT.md) files.'
        pr-message: 'Thank you for opening your first pull request! Please ensure you''ve read the [CONTRIBUTING.md](https://github.com/ouropencode/OpenDocumenter/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/ouropencode/OpenDocumenter/blob/master/CODE_OF_CONDUCT.md) files.'
